// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARTmGKn7njAwhdfiFVNkzOCAMdE7wMOD0',
    appId: '1:350230601450:web:a9e297beb3b29e6e278193',
    messagingSenderId: '350230601450',
    projectId: 'safestride-6129d',
    authDomain: 'safestride-6129d.firebaseapp.com',
    storageBucket: 'safestride-6129d.firebasestorage.app',
    measurementId: 'G-V57SB5VHQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq4uwzDcoeRxPnoHjpeNwchH9UjJBQh78',
    appId: '1:350230601450:android:a39e61c6d5b15b0b278193',
    messagingSenderId: '350230601450',
    projectId: 'safestride-6129d',
    storageBucket: 'safestride-6129d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSxlEhpCEVVcxx4er_0bdQul834bsjM1o',
    appId: '1:350230601450:ios:ec9b1fd022f3fc06278193',
    messagingSenderId: '350230601450',
    projectId: 'safestride-6129d',
    storageBucket: 'safestride-6129d.firebasestorage.app',
    iosClientId: '350230601450-ft26reublgjtsne8f5i5nj1pvivl96lo.apps.googleusercontent.com',
    iosBundleId: 'com.example.safestride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSxlEhpCEVVcxx4er_0bdQul834bsjM1o',
    appId: '1:350230601450:ios:ec9b1fd022f3fc06278193',
    messagingSenderId: '350230601450',
    projectId: 'safestride-6129d',
    storageBucket: 'safestride-6129d.firebasestorage.app',
    iosClientId: '350230601450-ft26reublgjtsne8f5i5nj1pvivl96lo.apps.googleusercontent.com',
    iosBundleId: 'com.example.safestride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARTmGKn7njAwhdfiFVNkzOCAMdE7wMOD0',
    appId: '1:350230601450:web:3657ea9a6f31030a278193',
    messagingSenderId: '350230601450',
    projectId: 'safestride-6129d',
    authDomain: 'safestride-6129d.firebaseapp.com',
    storageBucket: 'safestride-6129d.firebasestorage.app',
    measurementId: 'G-2DRRW1X967',
  );
}
